disable_ligatures always
cursor_shape beam
sync_to_monitor yes
repaint_delay 10
scrollback_lines 10000
input_delay 3
single_window_padding_width 4

# colors (pywal)
include ~/.cache/wal/colors-kitty.conf

# font stuff
font_size 14 
font_family      family="JetBrainsMonoNL Nerd Propo"
bold_font        auto
italic_font      auto
bold_italic_font auto
