hl.on("hyprland.start", function () 
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("protonvpn-app")
  hl.exec_cmd("waypaper --restore")
  hl.exec_cmd("quickshell -c ~/.config/quickshell")
end)
