# Default programs

$terminal = kitty
$browser = librewolf
$browser2 = chromium --disable-features=ExtensionManifestV2Unsupported,ExtensionManifestV2Disabled --password-store=basic
$browser3 = brave
$discord = discord
$fileManager = thunar
$menu = wofi --show drun
$screenshot = $HOME/.config/scripts/screenshot.sh
$music = spotify-launcher
$audio = pavucontrol

