# Main keys
$Mod1 = SUPER
$Mod2 = alt

# Shortcut binds
bind = $Mod1, Q, exec, $terminal
bind = $Mod1, N, exec, $browser
bind = $Mod1, R, exec, $menu
bind = $Mod1, E, exec, $fileManager
bind = $Mod1, S, exec, $screenshot
bind = $Mod1, M, exec, $music
bind = $Mod1, A, exec, $audio
bind = $Mod1, C, exec, $browser2
bind = $Mod1, D, exec, $discord
bind = $Mod1 SHIFT, N, exec, $browser3
bind = $Mod2, Q, killactive,
bind = $Mod1, F, fullscreen
bind = $Mod1 SHIFT, F, togglefloating, 
bind = $Mod1, W, exec, waypaper
bind = $Mod1, P, pseudo, # dwindle
bind = $Mod1, J, togglesplit, # dwindle
bind = $Mod1, V, togglefloating,

# Working with workspaces and windows
bind = $Mod1, 1, workspace, 1
bind = $Mod1, 2, workspace, 2
bind = $Mod1, 3, workspace, 3
bind = $Mod1, 4, workspace, 4
bind = $Mod1, 5, workspace, 5
bind = $Mod1, 6, workspace, 6
bind = $Mod1, 7, workspace, 7
bind = $Mod1, 8, workspace, 8
bind = $Mod1, 9, workspace, 9
bind = $Mod1, 0, workspace, 10

bind = $Mod2, 1, movetoworkspace, 1
bind = $Mod2, 2, movetoworkspace, 2
bind = $Mod2, 3, movetoworkspace, 3
bind = $Mod2, 4, movetoworkspace, 4
bind = $Mod2, 5, movetoworkspace, 5
bind = $Mod2, 6, movetoworkspace, 6
bind = $Mod2, 7, movetoworkspace, 7
bind = $Mod2, 8, movetoworkspace, 8
bind = $Mod2, 9, movetoworkspace, 9
bind = $Mod2, 0, movetoworkspace, 10

bind = $Mod1, Tab, cyclenext

bindm = $Mod1, mouse:272, movewindow
bindm = $Mod1, mouse:273, resizewindow
